name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: Geode-solutions/actions/.github/workflows/docker-build-squash-push.yml@master
    with:
      image_name: "ubuntu"
      tag: ${{ github.ref_name }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}